spring.datasource.url=${DBurl}
spring.datasource.username=${DBusername}
spring.datasource.password=${DBpassword}
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${jwt_secret}
jwt.expiration=${jwt_expiration}
file.upload-dir=uploads/sections
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB